remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Hello!]
description: [A wellcome page]
theme: Merlot_config.yml
